"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "ru" | "en";

type TranslationVars = Record<string, string | number>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, vars?: TranslationVars) => string;
};

const translations: Record<Language, Record<string, string>> = {
  ru: {
    "nav.home": "Главная",
    "nav.play": "Играть",
    "nav.learn": "Учиться",
    "nav.coach": "Разбор",
    "nav.tips": "Pro советы",
    "nav.rankings": "Рейтинг",
    "nav.account": "Профиль",

    "shell.tagline": "арена шашек",
    "shell.elite": "Elite user",
    "shell.becomeElite": "Стать Elite",
    "shell.signIn": "Войти",
    "shell.account": "Профиль",
    "language.ru": "RU",
    "language.en": "EN",

    "home.kicker": "CheckerX Arena",
    "home.title": "Играйте в шашки и растите как тактик.",
    "home.body": "Онлайн-арена для шашек с обязательными взятиями, подсказками ходов, разбором ошибок и видео-советами от сильных игроков по уровням.",
    "home.start": "Начать",
    "home.coachQuestion": "Тренер спрашивает: где обязательное взятие?",
    "home.loopKicker": "Цикл продукта",
    "home.loopTitle": "Учись, играй, разбирай, повторяй.",
    "home.buildKicker": "План развития",
    "home.buildTitle": "Что уже заложено в продукт",
    "home.learningTrack": "Открыть уроки",
    "home.startupKicker": "Startup angle",
    "home.startupTitle": "Не просто доска. Система тренировки шашек.",
    "home.startupBody": "CheckerX держится на возвращаемости: ежедневный XP, соперничество городов, разбор тренера, видео-советы и Elite-функции для глубокого анализа.",
    "home.coachDemo": "Демо разбора",
    "home.learn.title": "Учиться",
    "home.learn.body": "Короткие уроки формируют привычку сначала искать взятия.",
    "home.play.title": "Играть",
    "home.play.body": "Тренируйтесь с ботом, другом или на одном устройстве.",
    "home.review.title": "Разбор",
    "home.review.body": "Тренер превращает ошибки в повторяемые тактические задания.",
    "home.climb.title": "Рейтинг",
    "home.climb.body": "Сохраненные партии обновляют городские позиции и прогресс Elite.",
    "home.proof.captures": "Обязательные взятия",
    "home.proof.multijump": "Мульти-взятия",
    "home.proof.videos": "Видео от сильных игроков",
    "home.proof.vercel": "Готово к Vercel",
    "home.roadmap.now.title": "Сейчас",
    "home.roadmap.now.body": "Дизайн, маршруты, профиль и история продукта.",
    "home.roadmap.next.title": "Далее",
    "home.roadmap.next.body": "Игровой движок с обязательными взятиями, дамками и цепочками.",
    "home.roadmap.then.title": "Потом",
    "home.roadmap.then.body": "AI Coach, Pro советы, Supabase-комнаты и деплой на Vercel.",

    "page.account.kicker": "Supabase аккаунт",
    "page.account.title": "Сохраняйте партии, XP и рейтинг.",
    "page.account.body": "Создайте профиль CheckerX, синхронизируйте прогресс с Supabase и храните разборы партий в одном месте.",
    "page.play.kicker": "Играть",
    "page.play.title": "Играйте в настоящие шашки.",
    "page.play.body": "Легальные ходы, обязательные взятия, мульти-взятия, дамки, победитель, история ходов и уровни бота уже внутри доски.",
    "page.learn.kicker": "Обучение",
    "page.learn.title": "Короткие уроки шашек с XP.",
    "page.learn.body": "Проходите уроки по взятиям, мульти-взятиям, гонке в дамки и эндшпилям. Правильные ответы сохраняют XP в Supabase.",
    "page.coach.kicker": "AI тренер",
    "page.coach.title": "Превратите ошибку в тренировку.",
    "page.coach.body": "Тренер берет последнюю сохраненную партию из Supabase, оценивает ходы, объясняет взятия и рекомендует следующий урок.",
    "page.pro.kicker": "Elite user",
    "page.pro.title": "Монетизация без реальной оплаты.",
    "page.pro.body": "Активируйте демо Elite-статус в Supabase, получите бейдж и покажите бизнес-модель CheckerX.",
    "page.rankings.kicker": "Рейтинг городов",
    "page.rankings.title": "Поднимайтесь в локальной арене.",
    "page.rankings.body": "Сохраненные партии обновляют XP, рейтинг, оценку тренера и позицию в городе через Supabase.",
    "page.tips.kicker": "Pro советы",
    "page.tips.title": "Видео-советы по уровню.",
    "page.tips.body": "Открывайте YouTube-подборки по уровню, затем применяйте идеи в уроках, партиях и разборах CheckerX.",

    "stats.todayXp": "Сегодня XP",
    "stats.streak": "Серия",
    "stats.cityRank": "Ранг города",
    "stats.unranked": "Без ранга",
    "stats.days": "дн.",
    "stats.rating": "Рейтинг",
    "stats.coach": "Тренер",

    "account.login": "Войти",
    "account.register": "Регистрация",
    "account.email": "Email",
    "account.password": "Пароль",
    "account.passwordPlaceholder": "Минимум 6 символов",
    "account.playerName": "Имя игрока",
    "account.city": "Город",
    "account.level": "Уровень",
    "account.create": "Создать аккаунт",
    "account.signedIn": "Вы вошли",
    "account.signedInBody": "Играйте партии, проходите уроки, активируйте Elite, и прогресс останется в Supabase-профиле.",
    "account.profile": "Профиль игрока",
    "account.guest": "Гость",
    "account.loginToSync": "Войдите, чтобы синхронизировать прогресс.",
    "account.signOut": "Выйти",
    "account.save": "Сохранить",
    "account.recentGames": "Последние сохраненные партии",
    "account.noGames": "Пока нет сохраненных партий. Сыграйте матч и нажмите «Сохранить в Supabase».",
    "account.recommended": "Рекомендованные Pro советы",
    "account.openTips": "Открыть советы для моего уровня",
    "account.messageDefault": "Используйте Supabase-аккаунт, чтобы сохранять партии, XP и рейтинг города.",
    "account.loadError": "Не удалось загрузить Supabase-профиль.",
    "account.notConfigured": "Supabase пока не настроен.",
    "account.connecting": "Подключаемся к Supabase...",
    "account.created": "Аккаунт создан. Если включено подтверждение email, подтвердите почту перед входом.",
    "account.signedInMessage": "Вы вошли. CheckerX теперь может сохранять ваши партии.",
    "account.authFailed": "Авторизация не удалась.",
    "account.profileSaved": "Профиль сохранен.",
    "account.profileSaveError": "Не удалось сохранить профиль.",
    "account.signedOut": "Вы вышли.",
    "account.gameLocal": "локальная",
    "account.gameSaved": "сохранено",
    "account.gameMeta": "{date} · {moves} ходов · точность {accuracy}%",
    "account.level.beginner": "Новичок",
    "account.level.intermediate": "Средний",
    "account.level.advanced": "Продвинутый",
    "account.level.elite": "Elite",

    "tips.beginner": "Начните с обязательных взятий и базового видения доски.",
    "tips.intermediate": "Фокус на двойных взятиях, ловушках и форсированных цепочках.",
    "tips.advanced": "Изучайте гонку в дамки, размены и реализацию эндшпиля.",
    "tips.elite": "Тренируйте глубокий расчет и многоходовые форсированные варианты.",
    "tips.openYoutube": "Открыть видео на YouTube",
    "tips.level.beginner": "Новичок",
    "tips.level.club": "Клубный",
    "tips.level.advanced": "Продвинутый",
    "tips.level.pro": "Pro",
    "tips.tag.rules": "Правила",
    "tips.tag.tactics": "Тактика",
    "tips.tag.strategy": "Стратегия",
    "tips.tag.calculation": "Расчет",
    "tips.card.captures.title": "Сначала видеть все взятия",
    "tips.card.captures.advice": "Перед каждым ходом называйте вслух все возможные прыжки. Так быстрее всего уходят ошибки в правилах.",
    "tips.card.traps.title": "Строить ловушки на двойное взятие",
    "tips.card.traps.advice": "Смотрите на одну клетку приземления вперед. Хорошая ловушка приглашает соперника в ход, после которого открывается новая цепочка.",
    "tips.card.kings.title": "Размениваться в гонку дамок",
    "tips.card.kings.advice": "Не упрощайте позицию автоматически. Меняйтесь, когда ваша оставшаяся шашка быстрее проходит в дамки.",
    "tips.card.chains.title": "Считать форсированные цепочки",
    "tips.card.chains.advice": "Сначала выпишите кандидатные взятия, затем сравните финальный материал и доступ к дамочному ряду.",

    "game.level.beginner.title": "Новичок",
    "game.level.beginner.body": "Случайные легальные ходы",
    "game.level.club.title": "Клубный",
    "game.level.club.body": "Жадно берет фигуры",
    "game.level.elite.title": "Elite",
    "game.level.elite.body": "MiniMax расчет",
    "game.saveDefault": "Сохраните партию после нескольких ходов, чтобы синхронизировать XP и рейтинг.",
    "game.oneMoveRequired": "Сделайте хотя бы один ход перед сохранением.",
    "game.saving": "Сохраняем партию в Supabase...",
    "game.loginToSave": "Сначала войдите на странице профиля, затем сохраните партию.",
    "game.saved": "Сохранено. +{xp} XP, рейтинг {delta}.",
    "game.saveError": "Не удалось сохранить партию.",
    "game.white": "Белые",
    "game.black": "Черные",
    "game.wins": "{player} победили",
    "game.botThinking": "{bot} думает",
    "game.toMove": "Ход: {player}",
    "game.liveBoard": "Живая доска",
    "game.bot": "Бот",
    "game.twoPlayers": "2 игрока",
    "game.rule": "Правило",
    "game.captureRequired": "Нужно брать",
    "game.freeMove": "Свободный ход",
    "game.legalMoves": "Легальные ходы",
    "game.whitePieces": "Белые шашки",
    "game.blackPieces": "Черные шашки",
    "game.trainingBot": "Тренировочный бот",
    "game.chooseDifficulty": "Выберите сложность",
    "game.moveLog": "Лента ходов",
    "game.history": "История",
    "game.reset": "Сбросить партию",
    "game.firstMoveHint": "Сделайте первый ход. После выбора шашки легальные клетки подсветятся.",
    "game.human": "человек",
    "game.botSource": "бот",
    "game.coachReady": "Тренер готов",
    "game.coachReadyBody": "Эта доска уже создает настоящую историю ходов. Тренер сможет разобрать ошибки и превратить пропущенные взятия в задания.",
    "game.saveSupabase": "Сохранить в Supabase",
    "game.newGame": "Новая партия",
    "room.mode": "Комната",
    "room.kicker": "Мультиплеер",
    "room.title": "Комната с другом",
    "room.default": "Создайте комнату и отправьте код другу. Второй игрок вводит код здесь и подключается к той же доске.",
    "room.create": "Создать комнату",
    "room.join": "Войти",
    "room.codePlaceholder": "Код комнаты",
    "room.activeRoom": "Активная комната",
    "room.copy": "Копировать",
    "room.youAre": "Ваш цвет: {player}. Белые ходят первыми.",
    "room.spectator": "зритель",
    "room.creating": "Создаем комнату в Supabase...",
    "room.created": "Комната {code} создана. Отправьте код или ссылку другу.",
    "room.joining": "Подключаемся к комнате...",
    "room.joined": "Вы вошли в комнату {code}. Дождитесь своего хода.",
    "room.linkDetected": "В ссылке найден код {code}. Нажмите «Войти», чтобы подключиться.",
    "room.waiting": "Комната {code} ждет второго игрока.",
    "room.waitingStatus": "Комната {code}: ждем второго игрока",
    "room.yourTurn": "Ваш ход: {player}",
    "room.opponentTurn": "Ход соперника: {player}",
    "room.syncing": "Синхронизируем ход...",
    "room.synced": "Комната синхронизирована через Supabase Realtime.",
    "room.finished": "Партия в комнате завершена.",
    "room.resetDone": "Комната сброшена для новой партии.",
    "room.copied": "Ссылка/код комнаты скопированы.",
    "room.copyManual": "Скопируйте код вручную: {code}",
    "room.notConfigured": "Supabase Realtime не настроен. Проверьте URL, ключ и таблицу rooms.",
    "room.config": "Supabase Realtime не настроен.",
    "room.empty": "Введите код комнаты.",
    "room.not-found": "Комната с таким кодом не найдена.",
    "room.createError": "Не удалось создать комнату.",
    "room.joinError": "Не удалось войти в комнату.",
    "room.syncError": "Не удалось синхронизировать комнату.",

    "learn.defaultMessage": "Войдите, чтобы сохранять XP уроков, или проходите их локально как практику.",
    "learn.loaded": "Прогресс уроков из Supabase загружен.",
    "learn.loginAvailable": "Прогресс уроков доступен после входа.",
    "learn.tryAgain": "Попробуйте еще раз. Тренер ищет сильную привычку, а не просто легальный ход.",
    "learn.saving": "Сохраняем прогресс урока...",
    "learn.correctLogin": "Верно. Войдите на странице профиля, чтобы сохранить XP в Supabase.",
    "learn.alreadyDone": "Урок уже пройден. Повторный XP не начислен.",
    "learn.completed": "Урок пройден. +{xp} XP сохранено.",
    "learn.saveError": "Не удалось сохранить прогресс урока.",
    "learn.route": "Маршрут тренировки",
    "learn.completeCount": "{done}/{total} уроков пройдено",
    "learn.body": "Проходите короткие уроки перед рейтинговыми партиями. XP сохраняется в Supabase, когда вы вошли.",
    "learn.coachNote": "Заметка тренера",
    "learn.lesson": "Урок {number} / {level}",
    "learn.done": "Готово",
    "learn.practiceQuestion": "Практический вопрос",
    "learn.reviewLesson": "Повторить урок",
    "learn.completeLesson": "Завершить урок",
    "learn.answer.quiet": "Пойти любой шашкой вперед",
    "learn.answer.wait": "Ждать ошибки соперника",
    "lesson.forced-captures.title": "Обязательные взятия",
    "lesson.forced-captures.level": "Старт",
    "lesson.forced-captures.question": "Что нужно проверить перед каждым тихим ходом?",
    "lesson.forced-captures.answer": "Все доступные взятия",
    "lesson.forced-captures.coach": "Большинство поражений новичков начинается с пропущенных обязательных прыжков. Сначала проверьте обе диагонали, потом ходите.",
    "lesson.multi-jump-vision.title": "Видение мульти-взятия",
    "lesson.multi-jump-vision.level": "Тактика",
    "lesson.multi-jump-vision.question": "После первого взятия какая следующая привычка?",
    "lesson.multi-jump-vision.answer": "Искать новый прыжок с клетки приземления",
    "lesson.multi-jump-vision.coach": "Взятие не закончено, пока у шашки есть продолжение. CheckerX награждает полные цепочки.",
    "lesson.race-to-king-row.title": "Гонка в дамки",
    "lesson.race-to-king-row.level": "Стратегия",
    "lesson.race-to-king-row.question": "Почему открытая диагональ к последнему ряду опасна?",
    "lesson.race-to-king-row.answer": "Она может создать дамку",
    "lesson.race-to-king-row.coach": "При размене проверяйте, не получает ли соперник чистый маршрут к превращению.",
    "lesson.king-endgames.title": "Эндшпили с дамками",
    "lesson.king-endgames.level": "Продвинутый",
    "lesson.king-endgames.question": "Почему дамки сильнее обычных шашек?",
    "lesson.king-endgames.answer": "Они ходят и бьют назад",
    "lesson.king-endgames.coach": "Используйте дамки для контроля длинных диагоналей и вынуждайте соперника к плохим разменам.",

    "coach.loading": "Загружаем последнюю сохраненную партию...",
    "coach.loaded": "Последняя партия из Supabase загружена.",
    "coach.noGame": "Сохраненных партий пока нет. Сначала сыграйте и сохраните матч.",
    "coach.loginFirst": "Сначала войдите, затем сохраните партию для разбора.",
    "coach.savedMatch": "Сохраненная партия",
    "coach.noGameLoaded": "Партия не загружена",
    "coach.gameMeta": "{date} - {moves} ходов - {winner}",
    "coach.refresh": "Обновить разбор",
    "coach.verdict": "Вердикт тренера",
    "coach.accuracy": "Точность {accuracy}%",
    "coach.timeline": "Лента ходов",
    "coach.whatChanged": "Что изменилось",
    "coach.eliteReview": "Глубокий Elite-разбор",
    "coach.basicReview": "Базовый разбор",
    "coach.saveToUnlock": "Сохраните партию со страницы «Играть», чтобы открыть разбор по ходам.",
    "coach.quiet": "тихий",
    "coach.startDrill": "Начать рекомендованное задание",
    "coach.unlockDeep": "Открыть глубокий разбор",
    "coach.noGameSummary": "Сыграйте с ботом или локально, сохраните партию в Supabase, и тренер создаст здесь разбор.",
    "coach.nextAction": "Следующее действие",
    "coach.nextActionBody": "Перейдите в «Играть», сделайте несколько ходов и нажмите «Сохранить в Supabase».",
    "coach.savedSummary": "Партия успешно сохранена. Перед следующим матчем проверьте плотность взятий и доступ к дамочному ряду.",
    "coach.summary.light": "Белые закончили с перевесом. Проверьте, какие взятия и проходы в дамки дали лучший результат.",
    "coach.summary.dark": "Бот нашел более сильные форсированные линии. Разберите ленту ходов и найдите пропущенные шансы на взятие.",
    "coach.summary.draw": "Материал остался близким к равному. Следующая цель: повышать точность тихих ходов и не отдавать темп.",
    "coach.quietRisk": "Риск тихого хода",
    "coach.captureDiscipline": "Дисциплина взятий",
    "coach.quietRiskBody": "Тренер отметил {count} риск(а) тихого хода. Перед тихими ходами сканируйте все обязательные взятия.",
    "coach.captureBody": "Лента ходов показывает хорошую дисциплину взятий. Продолжайте проверять полные цепочки перед ходом.",
    "coach.bestMoment": "Лучший форсированный момент: {notation}",
    "coach.buildForcing": "Стройте форсированные ходы",
    "coach.bestMomentBody": "Этот ход взял {count} фигур(ы) и изменил материальный баланс.",
    "coach.noCaptureBody": "В сохранении нет взятий. Попробуйте создать позицию, где прыжок обязателен.",
    "coach.recommendedDrill": "Рекомендованное задание",
    "coach.drillMulti": "Откройте «Видение мульти-взятия» и тренируйтесь называть каждую клетку приземления.",
    "coach.drillKing": "Откройте эндшпили с дамками и превращайте материальный перевес в проход к дамке.",

    "elite.default": "Активируйте Elite Demo после входа. Реальная оплата не взимается.",
    "elite.activeMessage": "Elite user активен в вашем Supabase-профиле.",
    "elite.loginMessage": "Войдите на странице профиля, чтобы активировать Elite Demo.",
    "elite.activating": "Активируем Elite Demo...",
    "elite.loginFirst": "Сначала войдите на странице профиля, затем активируйте Elite Demo.",
    "elite.activated": "Elite Demo активирован. Бейдж теперь виден в профиле и рейтинге.",
    "elite.error": "Не удалось активировать Elite Demo.",
    "elite.demo": "Elite Demo",
    "elite.priceSuffix": "/мес демо",
    "elite.body": "Демо-монетизация прототипа: активируйте бейдж, откройте метки глубокого разбора и покажите бизнес-мышление без настоящей Stripe-оплаты.",
    "elite.currentStatus": "Текущий статус",
    "elite.active": "Elite user активен",
    "elite.free": "Бесплатный профиль",
    "elite.already": "Elite уже активен",
    "elite.activate": "Активировать Elite Demo",
    "elite.feature.payment": "Без реальной оплаты",
    "elite.feature.badge": "Elite бейдж",
    "elite.feature.skins": "Идея магазина скинов",
    "elite.feature.coach": "Глубокий AI тренер",
    "elite.benefit.review.title": "Глубокий разбор",
    "elite.benefit.review.body": "Более длинные объяснения тренера и метки риска для каждого хода.",
    "elite.benefit.drills.title": "Задания из ошибок",
    "elite.benefit.drills.body": "Каждое пропущенное взятие становится повторяемой карточкой-тренировкой.",
    "elite.benefit.badge.title": "Бейдж Elite user",
    "elite.benefit.badge.body": "Elite-статус отображается в рейтинге и профиле игрока.",
    "elite.benefit.skins.title": "Кастомные скины",
    "elite.benefit.skins.body": "Открывайте премиальные шашки и темы доски.",

    "rankings.loading": "Загружаем рейтинг Supabase...",
    "rankings.live": "Живой рейтинг Supabase.",
    "rankings.empty": "Игроков Supabase пока нет. Ниже показаны демо-игроки.",
    "rankings.demo": "Показываем демо-рейтинг.",
    "rankings.loginRequired": "Для живого рейтинга нужен вход: {message}",
    "rankings.liveArena": "Живая арена",
    "rankings.rank": "Ранг",
    "rankings.player": "Игрок",
    "rankings.city": "Город",
    "rankings.rating": "Рейтинг",
    "rankings.badge": "Бейдж",
    "rankings.coachScore": "Оценка тренера {score}",
    "rankings.badgeElite": "Elite user",
    "rankings.badgeClimber": "Растет в городе",
    "rankings.badgeNew": "Новый",
  },
  en: {
    "nav.home": "Home",
    "nav.play": "Play",
    "nav.learn": "Learn",
    "nav.coach": "Coach",
    "nav.tips": "Pro Tips",
    "nav.rankings": "Rankings",
    "nav.account": "Account",

    "shell.tagline": "checkers arena",
    "shell.elite": "Elite user",
    "shell.becomeElite": "Become Elite",
    "shell.signIn": "Sign in",
    "shell.account": "Account",
    "language.ru": "RU",
    "language.en": "EN",

    "home.kicker": "CheckerX Arena",
    "home.title": "Play checkers and grow as a tactician.",
    "home.body": "An online checkers arena with mandatory captures, move hints, mistake review, and video advice from strong players by level.",
    "home.start": "Start",
    "home.coachQuestion": "Coach asks: where is the forced jump?",
    "home.loopKicker": "Product loop",
    "home.loopTitle": "Learn, play, review, repeat.",
    "home.buildKicker": "Build path",
    "home.buildTitle": "What is built into the product",
    "home.learningTrack": "View learning track",
    "home.startupKicker": "Startup angle",
    "home.startupTitle": "Not just a board. A checkers training system.",
    "home.startupBody": "CheckerX is built around retention: daily XP, city rivalry, coach feedback, pro video advice, and Elite features for deeper analysis.",
    "home.coachDemo": "Coach demo",
    "home.learn.title": "Learn",
    "home.learn.body": "Short lessons build the habit of checking captures first.",
    "home.play.title": "Play",
    "home.play.body": "Train with a bot, invite a friend, or play on one device.",
    "home.review.title": "Review",
    "home.review.body": "The coach turns mistakes into replayable tactical cards.",
    "home.climb.title": "Climb",
    "home.climb.body": "Saved matches update city rank and Elite progress.",
    "home.proof.captures": "Forced captures",
    "home.proof.multijump": "Multi-jump rules",
    "home.proof.videos": "Pro-player videos",
    "home.proof.vercel": "Vercel-ready app",
    "home.roadmap.now.title": "Now",
    "home.roadmap.now.body": "Design shell, routes, profile, and product story.",
    "home.roadmap.next.title": "Next",
    "home.roadmap.next.body": "Checkers engine with forced captures, kings, and jump chains.",
    "home.roadmap.then.title": "Then",
    "home.roadmap.then.body": "AI Coach, Pro Tips, Supabase rooms, and Vercel deploy.",

    "page.account.kicker": "Supabase account",
    "page.account.title": "Save games, XP, and rank.",
    "page.account.body": "Create a CheckerX profile, sync progress to Supabase, and keep your reviewed games in one place.",
    "page.play.kicker": "Play",
    "page.play.title": "Play real checkers.",
    "page.play.body": "Legal moves, mandatory captures, multi-jumps, kings, victory detection, move history, and bot levels are now inside the board.",
    "page.learn.kicker": "Learn",
    "page.learn.title": "Short checkers lessons with XP.",
    "page.learn.body": "Complete capture, multi-jump, king-race, and endgame lessons. Correct answers save XP and progress to Supabase.",
    "page.coach.kicker": "AI Coach",
    "page.coach.title": "Turn a mistake into a drill.",
    "page.coach.body": "The coach loads your latest saved Supabase game, scores the move log, explains capture discipline, and recommends the next lesson.",
    "page.pro.kicker": "Elite user",
    "page.pro.title": "A monetization path without real payments yet.",
    "page.pro.body": "Activate a demo Elite status in Supabase, unlock a visible badge, and show how CheckerX can monetize deeper training.",
    "page.rankings.kicker": "City rankings",
    "page.rankings.title": "Climb your local arena.",
    "page.rankings.body": "Saved games update XP, rating, coach score, and city rank through Supabase.",
    "page.tips.kicker": "Pro Tips",
    "page.tips.title": "Video advice by skill level.",
    "page.tips.body": "Open curated YouTube searches for each level, then bring the idea back into CheckerX lessons, games, and coach review.",

    "stats.todayXp": "Today XP",
    "stats.streak": "Current streak",
    "stats.cityRank": "City rank",
    "stats.unranked": "Unranked",
    "stats.days": "days",
    "stats.rating": "Rating",
    "stats.coach": "Coach",

    "account.login": "Login",
    "account.register": "Register",
    "account.email": "Email",
    "account.password": "Password",
    "account.passwordPlaceholder": "At least 6 characters",
    "account.playerName": "Player name",
    "account.city": "City",
    "account.level": "Level",
    "account.create": "Create account",
    "account.signedIn": "You are signed in",
    "account.signedInBody": "Play games, complete lessons, activate Elite, and your progress will stay attached to this Supabase profile.",
    "account.profile": "Player profile",
    "account.guest": "Guest player",
    "account.loginToSync": "Login to sync progress.",
    "account.signOut": "Sign out",
    "account.save": "Save",
    "account.recentGames": "Recent saved games",
    "account.noGames": "No saved games yet. Play a match, then press Save to Supabase.",
    "account.recommended": "Recommended Pro Tips",
    "account.openTips": "Open tips for my level",
    "account.messageDefault": "Use your Supabase account to save games, XP, and city rank.",
    "account.loadError": "Could not load Supabase profile.",
    "account.notConfigured": "Supabase is not configured yet.",
    "account.connecting": "Connecting to Supabase...",
    "account.created": "Account created. If email confirmation is enabled, confirm the email before login.",
    "account.signedInMessage": "Signed in. CheckerX can now save your games.",
    "account.authFailed": "Auth failed.",
    "account.profileSaved": "Profile saved.",
    "account.profileSaveError": "Could not save profile.",
    "account.signedOut": "Signed out.",
    "account.gameLocal": "local",
    "account.gameSaved": "saved",
    "account.gameMeta": "{date} · {moves} moves · accuracy {accuracy}%",
    "account.level.beginner": "Beginner",
    "account.level.intermediate": "Intermediate",
    "account.level.advanced": "Advanced",
    "account.level.elite": "Elite",

    "tips.beginner": "Start with mandatory captures and basic board vision.",
    "tips.intermediate": "Focus on double-jump traps and forcing sequences.",
    "tips.advanced": "Study king races, trades, and endgame conversion.",
    "tips.elite": "Train deep calculation and multi-move forcing chains.",
    "tips.openYoutube": "Open YouTube videos",
    "tips.level.beginner": "Beginner",
    "tips.level.club": "Club",
    "tips.level.advanced": "Advanced",
    "tips.level.pro": "Pro",
    "tips.tag.rules": "Rules",
    "tips.tag.tactics": "Tactics",
    "tips.tag.strategy": "Strategy",
    "tips.tag.calculation": "Calculation",
    "tips.card.captures.title": "See all legal captures first",
    "tips.card.captures.advice": "Pause before every move and name each jump out loud. This fixes most rule-level mistakes.",
    "tips.card.traps.title": "Build double-jump traps",
    "tips.card.traps.advice": "Look one landing square ahead. Good traps invite a capture that leaves the next jump open.",
    "tips.card.kings.title": "Trade into king races",
    "tips.card.kings.advice": "Do not trade just to simplify. Trade when your remaining piece promotes faster.",
    "tips.card.chains.title": "Calculate forcing chains",
    "tips.card.chains.advice": "Write down candidate captures first, then compare final material and king-row access.",

    "game.level.beginner.title": "Beginner",
    "game.level.beginner.body": "Random legal moves",
    "game.level.club.title": "Club",
    "game.level.club.body": "Greedy captures",
    "game.level.elite.title": "Elite",
    "game.level.elite.body": "MiniMax review",
    "game.saveDefault": "Save a game after a few moves to sync XP and rating.",
    "game.oneMoveRequired": "Make at least one move before saving.",
    "game.saving": "Saving game to Supabase...",
    "game.loginToSave": "Login on the Account page first, then save the game.",
    "game.saved": "Saved. +{xp} XP, rating {delta}.",
    "game.saveError": "Could not save the game.",
    "game.white": "White",
    "game.black": "Black",
    "game.wins": "{player} wins",
    "game.botThinking": "{bot} bot is thinking",
    "game.toMove": "{player} to move",
    "game.liveBoard": "Live board",
    "game.bot": "Bot",
    "game.twoPlayers": "2 players",
    "game.rule": "Rule",
    "game.captureRequired": "Capture required",
    "game.freeMove": "Free move",
    "game.legalMoves": "Legal moves",
    "game.whitePieces": "White pieces",
    "game.blackPieces": "Black pieces",
    "game.trainingBot": "Training bot",
    "game.chooseDifficulty": "Choose difficulty",
    "game.moveLog": "Move log",
    "game.history": "History",
    "game.reset": "Reset game",
    "game.firstMoveHint": "Make the first move. Legal squares will highlight after you select a piece.",
    "game.human": "human",
    "game.botSource": "bot",
    "game.coachReady": "Coach ready",
    "game.coachReadyBody": "This board already produces real move history. The coach can review these moves and turn missed captures into training tasks.",
    "game.saveSupabase": "Save to Supabase",
    "game.newGame": "New game",
    "room.mode": "Room",
    "room.kicker": "Multiplayer",
    "room.title": "Friend room",
    "room.default": "Create a room and send the code to a friend. The second player enters the code here and joins the same board.",
    "room.create": "Create room",
    "room.join": "Join",
    "room.codePlaceholder": "Room code",
    "room.activeRoom": "Active room",
    "room.copy": "Copy",
    "room.youAre": "Your side: {player}. White moves first.",
    "room.spectator": "spectator",
    "room.creating": "Creating Supabase room...",
    "room.created": "Room {code} created. Send the code or link to your friend.",
    "room.joining": "Joining room...",
    "room.joined": "You joined room {code}. Wait for your turn.",
    "room.linkDetected": "Found room code {code} in the link. Press Join to connect.",
    "room.waiting": "Room {code} is waiting for the second player.",
    "room.waitingStatus": "Room {code}: waiting for second player",
    "room.yourTurn": "Your turn: {player}",
    "room.opponentTurn": "Opponent turn: {player}",
    "room.syncing": "Syncing move...",
    "room.synced": "Room synced through Supabase Realtime.",
    "room.finished": "Room game finished.",
    "room.resetDone": "Room reset for a new game.",
    "room.copied": "Room link/code copied.",
    "room.copyManual": "Copy this code manually: {code}",
    "room.notConfigured": "Supabase Realtime is not configured. Check URL, key, and the rooms table.",
    "room.config": "Supabase Realtime is not configured.",
    "room.empty": "Enter a room code.",
    "room.not-found": "Room code not found.",
    "room.createError": "Could not create room.",
    "room.joinError": "Could not join room.",
    "room.syncError": "Could not sync room.",

    "learn.defaultMessage": "Login to save lesson XP, or use lessons locally as practice.",
    "learn.loaded": "Your Supabase lesson progress is loaded.",
    "learn.loginAvailable": "Lesson progress is available after login.",
    "learn.tryAgain": "Try again. The coach wants the strongest habit, not just a legal move.",
    "learn.saving": "Saving lesson progress...",
    "learn.correctLogin": "Correct. Login on Account page to save XP in Supabase.",
    "learn.alreadyDone": "Lesson already completed. No duplicate XP added.",
    "learn.completed": "Lesson completed. +{xp} XP saved.",
    "learn.saveError": "Could not save lesson progress.",
    "learn.route": "Training route",
    "learn.completeCount": "{done}/{total} lessons complete",
    "learn.body": "Complete short lessons to build habits before ranked games. XP is stored in Supabase when you are signed in.",
    "learn.coachNote": "Coach note",
    "learn.lesson": "Lesson {number} / {level}",
    "learn.done": "Done",
    "learn.practiceQuestion": "Practice question",
    "learn.reviewLesson": "Review lesson",
    "learn.completeLesson": "Complete lesson",
    "learn.answer.quiet": "Move any checker forward",
    "learn.answer.wait": "Wait for the opponent mistake",
    "lesson.forced-captures.title": "Forced captures",
    "lesson.forced-captures.level": "Starter",
    "lesson.forced-captures.question": "What should you check before every quiet move?",
    "lesson.forced-captures.answer": "All available captures",
    "lesson.forced-captures.coach": "Most beginner losses come from missing mandatory jumps. Scan both diagonals first, then move.",
    "lesson.multi-jump-vision.title": "Multi-jump vision",
    "lesson.multi-jump-vision.level": "Tactics",
    "lesson.multi-jump-vision.question": "After the first capture, what is the next habit?",
    "lesson.multi-jump-vision.answer": "Look for another jump from the landing square",
    "lesson.multi-jump-vision.coach": "A capture is not finished until the piece has no further jump. CheckerX rewards full chains.",
    "lesson.race-to-king-row.title": "Race to king row",
    "lesson.race-to-king-row.level": "Strategy",
    "lesson.race-to-king-row.question": "Why is an open diagonal to the back row dangerous?",
    "lesson.race-to-king-row.answer": "It can create a king",
    "lesson.race-to-king-row.coach": "When you trade, check whether the opponent gets a clean route to promotion.",
    "lesson.king-endgames.title": "King endgames",
    "lesson.king-endgames.level": "Advanced",
    "lesson.king-endgames.question": "What makes kings stronger than normal pieces?",
    "lesson.king-endgames.answer": "They can move and capture backward",
    "lesson.king-endgames.coach": "Use kings to control long diagonals and force the opponent into bad trades.",

    "coach.loading": "Loading your latest saved game...",
    "coach.loaded": "Latest Supabase game loaded.",
    "coach.noGame": "No saved game yet. Play and save a match first.",
    "coach.loginFirst": "Login first, then save a game for review.",
    "coach.savedMatch": "Saved match",
    "coach.noGameLoaded": "No game loaded",
    "coach.gameMeta": "{date} - {moves} moves - {winner}",
    "coach.refresh": "Refresh review",
    "coach.verdict": "Coach verdict",
    "coach.accuracy": "Accuracy {accuracy}%",
    "coach.timeline": "Move timeline",
    "coach.whatChanged": "What changed",
    "coach.eliteReview": "Elite deep review",
    "coach.basicReview": "Basic review",
    "coach.saveToUnlock": "Save a game from the Play page to unlock move-by-move review.",
    "coach.quiet": "quiet",
    "coach.startDrill": "Start recommended drill",
    "coach.unlockDeep": "Unlock deep review",
    "coach.noGameSummary": "Play a bot or local match, save it to Supabase, and the coach will create a review here.",
    "coach.nextAction": "Next action",
    "coach.nextActionBody": "Go to Play, make a few moves, then press Save to Supabase.",
    "coach.savedSummary": "The game was saved successfully. Review capture density and king-row access before your next match.",
    "coach.summary.light": "White finished with the advantage. Review which captures and promotion paths created the result.",
    "coach.summary.dark": "The bot found stronger forcing lines. Review the move log for missed capture chances.",
    "coach.summary.draw": "The material stayed close. Your next goal is cleaner quiet moves without giving away tempo.",
    "coach.quietRisk": "Quiet move risk",
    "coach.captureDiscipline": "Capture discipline",
    "coach.quietRiskBody": "The coach marked {count} quiet-move risk(s). Before quiet moves, scan all forced jumps.",
    "coach.captureBody": "Your move log shows solid capture discipline. Keep checking full chains before moving.",
    "coach.bestMoment": "Best forcing moment: {notation}",
    "coach.buildForcing": "Build forcing moves",
    "coach.bestMomentBody": "This move captured {count} piece(s) and changed the material balance.",
    "coach.noCaptureBody": "No captures were saved. Try creating a position where a jump is mandatory.",
    "coach.recommendedDrill": "Recommended drill",
    "coach.drillMulti": "Open Multi-jump vision and practice naming every landing square.",
    "coach.drillKing": "Open King endgames and convert material into promotion paths.",

    "elite.default": "Activate Elite Demo after login. No real payment is collected.",
    "elite.activeMessage": "Elite user is active on your Supabase profile.",
    "elite.loginMessage": "Login on Account page to activate Elite Demo.",
    "elite.activating": "Activating Elite Demo...",
    "elite.loginFirst": "Login on Account page first, then activate Elite Demo.",
    "elite.activated": "Elite Demo activated. Your badge is now visible in profile and leaderboard.",
    "elite.error": "Could not activate Elite Demo.",
    "elite.demo": "Elite Demo",
    "elite.priceSuffix": "/mo demo",
    "elite.body": "Demo monetization for the prototype: activate the badge, unlock deep review labels, and show business thinking without real Stripe charges.",
    "elite.currentStatus": "Current status",
    "elite.active": "Elite user active",
    "elite.free": "Free profile",
    "elite.already": "Elite already active",
    "elite.activate": "Activate Elite Demo",
    "elite.feature.payment": "No real payment",
    "elite.feature.badge": "Elite badge",
    "elite.feature.skins": "Skin marketplace idea",
    "elite.feature.coach": "Deeper AI coach",
    "elite.benefit.review.title": "Deep review",
    "elite.benefit.review.body": "Longer coach explanations and move-by-move risk labels.",
    "elite.benefit.drills.title": "Mistake drills",
    "elite.benefit.drills.body": "Every missed capture becomes a repeatable puzzle card.",
    "elite.benefit.badge.title": "Elite user badge",
    "elite.benefit.badge.body": "Elite user status appears in rankings and the player profile.",
    "elite.benefit.skins.title": "Custom skins",
    "elite.benefit.skins.body": "Unlock premium checker pieces and board themes.",

    "rankings.loading": "Loading Supabase leaderboard...",
    "rankings.live": "Live Supabase leaderboard.",
    "rankings.empty": "No Supabase players yet. Showing demo players below.",
    "rankings.demo": "Showing demo leaderboard.",
    "rankings.loginRequired": "Login required for live leaderboard: {message}",
    "rankings.liveArena": "Live arena",
    "rankings.rank": "Rank",
    "rankings.player": "Player",
    "rankings.city": "City",
    "rankings.rating": "Rating",
    "rankings.badge": "Badge",
    "rankings.coachScore": "Coach score {score}",
    "rankings.badgeElite": "Elite user",
    "rankings.badgeClimber": "City climber",
    "rankings.badgeNew": "New",
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function readSavedLanguage(): Language {
  if (typeof window === "undefined") {
    return "ru";
  }

  try {
    const saved = window.localStorage?.getItem("checkerx-language");
    if (saved === "ru" || saved === "en") {
      return saved;
    }
  } catch {
    // Some embedded browser contexts can block storage; cookies keep the toggle usable.
  }

  const cookieLanguage = document.cookie
    .split(";")
    .map((item) => item.trim())
    .find((item) => item.startsWith("checkerx-language="))
    ?.split("=")[1];

  return cookieLanguage === "en" || cookieLanguage === "ru" ? cookieLanguage : "ru";
}

function persistLanguage(language: Language) {
  try {
    window.localStorage?.setItem("checkerx-language", language);
  } catch {
    // Cookie fallback below is enough when localStorage is not available.
  }

  try {
    document.cookie = `checkerx-language=${language}; path=/; max-age=31536000; SameSite=Lax`;
  } catch {
    // The language still changes in the current app session.
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => readSavedLanguage());

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  function setLanguage(nextLanguage: Language) {
    setLanguageState(nextLanguage);
    persistLanguage(nextLanguage);
    document.documentElement.lang = nextLanguage;
  }

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string, vars?: TranslationVars) => {
        const template = translations[language][key] ?? translations.en[key] ?? key;
        if (!vars) {
          return template;
        }

        return Object.entries(vars).reduce(
          (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
          template,
        );
      },
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useI18n() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useI18n must be used inside LanguageProvider");
  }

  return context;
}
